#!/usr/bin/env bash
# =============================================================================
# setup-gitconfig.sh — Generate ~/.gitconfig as an include-only stub
#
# Called by install.sh, or run directly:
#   bash ~/dotfiles/setup-gitconfig.sh [--dry-run]
#
# Why this exists (and why ~/.gitconfig is the one dotfile that is NOT a
# symlink into this repo):
#
#   `git config --global ...` always WRITES to ~/.gitconfig. When that path is
#   a symlink into this repo, those writes land in the tracked file — so
#   anything calling it behind your back commits machine-local state into a
#   public repo. That is not hypothetical: a self-hosted CI runner repeatedly
#   running `git config --global --add safe.directory <runner path>` appended
#   955 duplicate lines of local paths to the tracked `gitconfig`.
#
#   So we generate ~/.gitconfig as a small REAL file that just includes:
#     1. this repo's `gitconfig`   (shared, tracked config)
#     2. ~/.gitconfig.local        (identity + machine-local settings)
#   Global writes then accumulate in the untracked stub, out of the repo.
#   Later includes win, so ~/.gitconfig.local still overrides repo defaults.
#
#   Corollary: the tracked `gitconfig` must NOT include ~/.gitconfig.local
#   itself — the stub already includes it afterwards, and including it twice
#   duplicates every multi-valued key (safe.directory, and any *.insteadOf).
#
# Idempotent, like every other install step:
#   - already-correct stub  → left completely alone, so settings accumulated
#                             in it by `git config --global` survive a re-run
#   - old-style symlink     → replaced in place (carries no unique state)
#   - unmanaged real file   → backed up to ~/.gitconfig.bak first
#   - no file at all        → created
#
# NOTE for existing checkouts: a machine that pulls this repo but does not
# re-run install.sh keeps the old symlink, which no longer includes
# ~/.gitconfig.local — that machine loses its git identity until this script
# runs. Re-run it (or install.sh) once per machine after pulling.
# =============================================================================

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
for arg in "$@"; do
    [[ "$arg" == "--dry-run" ]] && DRY_RUN=true
done

log()  { echo "  → $*"; }
ok()   { echo "  ✓ $*"; }

DST="$HOME/.gitconfig"
TRACKED="$DOTFILES_DIR/gitconfig"

echo ""
echo "=== gitconfig setup ==="
echo ""

if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] write include-only $DST (includes $TRACKED, then ~/.gitconfig.local)"
    exit 0
fi

# Leave an already-correct stub alone: re-running install.sh must not discard
# whatever `git config --global` has written into it since.
if [[ -f "$DST" && ! -L "$DST" ]] \
    && grep -qxF "	path = $TRACKED" "$DST" \
    && grep -qxF "	path = ~/.gitconfig.local" "$DST"; then
    ok "$DST already an include-only stub — left as-is"
    exit 0
fi

if [[ -L "$DST" ]]; then
    # An old-style symlink into this repo carries no unique state — the tracked
    # file is still included below — so drop it rather than leave a stale .bak.
    rm "$DST"
    log "replaced old symlink $DST"
elif [[ -e "$DST" ]]; then
    # Don't clobber a previous backup that may hold the only copy of something.
    BAK="$DST.bak"
    if [[ -e "$BAK" ]]; then
        BAK="$DST.bak.$(date +%Y%m%d%H%M%S)"
    fi
    mv "$DST" "$BAK"
    log "backed up existing $DST -> $BAK"
fi

cat > "$DST" <<EOF
# Generated by $DOTFILES_DIR/setup-gitconfig.sh — NOT tracked by the dotfiles repo.
#
# Shared config lives in $TRACKED; identity and machine-local
# settings in ~/.gitconfig.local (later include wins).
#
# Anything \`git config --global\` writes is appended below. That is the point:
# it keeps machine-local state out of the public dotfiles repo.
[include]
	path = $TRACKED
[include]
	path = ~/.gitconfig.local
EOF

ok "wrote include-only $DST"
